import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { getProducts } from "../lib/paddle";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Next.js Paddle Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto px-20 py-10">
        <h1 className="text-xl font-bold">Products</h1>

        <div className="mt-10 grid grid-cols-3 gap-x-16 gap-y-20">
          {products.map((product) => (
            <Link href={`/products/${product.id}`} key={product.id}>
              <a>
                <Image width={800} height={508} src={product.icon} alt={product.title} />
                <p>{product.name}</p>
                <p className="text-sm text-gray-500">{product.description}</p>
                <p className="text-sm mt-2">${product.base_price}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await getProducts();
  return {
    props: {
      products,
    },
  };
}
